### ISSUE TITLE
Agreement to participate

### ISSUE THREAD

**Issue by dzabraev** [usnistgov/frvt#13]
Is it enough to sign [this document](https://www.nist.gov/sites/default/files/documents/2019/04/22/frvt_1n_participation_agreement.pdf) for participation in 1v1 and 1vN or is it needed to sign [this](https://www.nist.gov/sites/default/files/documents/2016/12/15/frvt_participation_agreement.pdf) document too?

**Comment by mlngan** [comment]
You need to sign separate participation agreements for 1:1 versus 1:N.

**Comment by dzabraev** [comment]
Currently we are going to participate in **1:N** and already signed and sent by post the signed document https://www.nist.gov/sites/default/files/documents/2019/04/22/frvt_1n_participation_agreement.pdf (the one that is mentioned on 1:N page). 

As we need to pass some 1:1 thresholds, do we need to **additionally** sign and send the document mentioned on **1:1** page (we don't want participate in 1:1, at least for now) https://www.nist.gov/sites/default/files/documents/2016/12/15/frvt_participation_agreement.pdf ?

**Comment by mlngan** [comment]
As published on our 1:N website:
In order to participate in FRVT 1:N, participants must submit at least one algorithm to the FRVT 1:1 track, and its accuracy must exceed at least one of the following:

VisaMC dataset: FNMR of 0.025 or less at FMR=0.0001 OR
Mugshot dataset: FNMR of 0.025 or less at FMR=0.00001

Once an organization submits a 1:1 algorithm that exceeds the minimum accuracy requirements, that organization may submit algorithms to the 1:N track thereafter.

**Comment by quocnhat** [comment]
hi @mlngan ,
as your mentioned, in order to participate FRVT 1:N, the FRVT 1:1 accuracy must pass some requirements. But I find that @NEC performs very well on the FRVT 1:N leaderboard, but they are empty from FRVT 1:1 leaderboard. 
How was it? thank you.

**Comment by mlngan** [comment]
Hi - we removed the 1:1 submission requirement in order to participate in 1:N some time ago, so developers can submit directly to the 1:N track if they choose.
