### ISSUE TITLE
Time assessment for template creation

### ISSUE THREAD

**Issue by gasgallo** [usnistgov/frvt#15]
Is it possible to have a brief description about the procedure used to assess the time required to create a template?
More specifically, I'm interested in understanding the batch size (namely, how many images are tested before calling `initialize` function again).

Thank you.

**Comment by mlngan** [comment]
For timing, we call 1) initialize() 2) createTemplate() with single image inputs multiple times.  Initialize isn't called again after the first call to createTemplate().

**Comment by ElisonSherton** [comment]
Hi @mlngan 

If a few of the samples take more than 1500 ms for template creation, would it mean the template computation would be terminated abruptly or does it mean template would be computed but not considered for the scoring?

Consider if 10 samples are taking 1510 ms for template creation due to some issue, will those 10 samples be considered in scoring process or not?

Thanks,
Vinayak

**Comment by ElisonSherton** [comment]
Thank you so much! Got it.
