### ISSUE TITLE
Can I load the models in the constructor? 

### ISSUE THREAD

**Issue by wfcb-85** [usnistgov/frvt#48]
Hello, 

When I execute run_validate.sh, it does not seem to be calling the initialize function. I don't see the messages I print nor a change of the values of the variables. Would it be a problem if I loaded the model files within the constructor?

**Comment by mlngan** [comment]
The initialize() function is called in the testdriver provided in the validation package - https://github.com/usnistgov/frvt/blob/master/11/src/testdriver/validate11.cpp

Did you follow the instructions contained in the README.md file on putting your library into ./lib?  Or did you optionally build the null sdk?  Did you successfully compile and link your library against the provided testdriver - e.g. did you see any errors when you ran run_validate_11.sh?  Additionally, the path to the configuration directory that you will read your models from is passed in as a parameter to initialize().  Please do not hard-code your configuration directory, because it will not be in the same location on our systems.

**Comment by wfcb-85** [comment]
It works when I build the null sdk.
