### ISSUE TITLE
Distribution of actual matches during validation 

### ISSUE THREAD

**Issue by tanpengshi** [usnistgov/frvt#82]
Hello, I have successfully ran the validation, and it seems that vast majority of matching has very high similarity scores, except for only 1. May I know if that is the norm for the validation package? Are these comparisons suppose to be matches? What should be the distribution of matches in the validation?

Thank you!

**Comment by xsacha** [comment]
This is heavily implementation dependent.
In the validation package, some of the pairs are incorrect (you can tell because the IDs are different). A match is expected when the ID is the same.

Here's an example output with 'distance' (opposite of similarity) vs expected match for a solution that gets 100% in validation
[v8.txt](https://github.com/usnistgov/frvt/files/9920710/v8.txt)
